# Generated by Django 6.0.5 on 2026-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('required_skills', models.CharField(max_length=30)),
                ('created_time', models.DateTimeField()),
            ],
        ),
    ]
