# Generated by Django 6.0.5 on 2026-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_applicant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='candidate_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='skills',
            field=models.CharField(max_length=55),
        ),
    ]
