# Generated by Django 6.0.5 on 2026-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_applicant_candidate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
