# Generated by Django 6.0.5 on 2026-05-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_applicant_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='skills',
            new_name='candidate_skills',
        ),
    ]
